### ISSUE TITLE
Nuke USD plugin "Lock Frame" function doesn't honor "set_frame" knob

### ISSUE THREAD

**Issue by morgan-cg** [dreamworksanimation/dwa_usd_plugins#10]
Greetings!

It looks as though the "lock frame" function in the readgeo node isn't working as expected.  Instead of locking to the frame number in the "set read frame" knob, it seems like it uses a static frame number (likely frame 1).

Also a minor note from some of our users. The verbiage used for the lock frame checkbox was a little confusing and makes it look as though frame locking is on by default when it isn't.  I think either reversing the checkbox behavior (no check = read every frame, check = frame lock) or changing the label to something like "read each frame" might make that function a little more user friendly.

Please let me know if there are any questions or would like additional info.

Many Thanks!
Morgan

**Comment by jegstad-dwa** [comment]
Yeah that looks like an incomplete thought. The Fuser/GeoReader panel is a rewrite of an older one I initially wrote at DWA for Alembic importing and I was updating some of the knobs for usd and deprecating others.

The older knob was 'read on each frame' defaulted to on, which is poor default logic so I was changing it to 'lock frame' defaulted to off, so turning it on would then enable the 'set read frame' knob. But it appears I didn't finish that thought which is why the knob seems to do the wrong thing by default.

I'll finish updating it to 'lock frame', defaulted off which should be intuitive for users.

btw there's several other knobs on that panel that are holdovers from the previous Alembic version which may not be working anymore or are too 'DWA', like 'ignore unrenderable', 'apply matrix', 'translate render parts to UDIMs', 'snap to limit', etc. so please feel free to request features here as I haven't had time to tune up that stuff.
For example the subd options are not particularly fleshed out.

For reference here's the older ReadGeo panel before the open source changes:
![readgeo_previous](https://user-images.githubusercontent.com/62024730/89679885-cafd7380-d8a6-11ea-8b50-d1579174ca0d.png)

**Comment by jegstad-dwa** [comment]
This is cleaned up and the time controls made more intuitive in general, as well as adding better support for time warping and offsetting of the input animation.
