### ISSUE TITLE
Nuke USD plugin does not support instanced geometry

### ISSUE THREAD

**Issue by morgan-cg** [dreamworksanimation/dwa_usd_plugins#6]
Greetings!
I wanted to log this issue on its own to continue discussion on adding support for instanced geometry to the Nuke USD plugin.  

I checked into providing a test scene with examples of instancing and it does appear that the Kitchen test scene provided by Pixar has two versions with and without instancing. Here is the path to the kitchen set I tested: http://graphics.pixar.com/usd/downloads.html

Let me know your thoughts on adding basic support for instancing.  I think starting with a deferred-loading option makes sense to me and will let us test to see how well Nuke's 3D system can handle (or can't handle as the case may be) an average scene we'll be using in production.  Certainly of course, I'm open to other suggestions and ideas for first steps that we can try as well!

Cheers,
Morgan

**Comment by jegstad-dwa** [comment]
Hi Morgan,

Finally looking at this and it's simpler than I feared it would be. When I was thinking 'instanced geometry' I was thinking the 'thousands of leaves on a tree in a forest of trees' kind of instancing. ie UsdGeomPointInstancer.

However it appears the basic scenegraph prim instancing supported by usd is not addressed when you use UsdPrim::GetAllChidlren(), which I naively thought would get me all the prim's children...silly me. The right method to use is GetAllFilteredChildren() with the UsdTraverseInstanceProxies() predicate enabled.

So that simple change gets all the instanced prims and Nuke is copying them so they're no longer instanced, but at least they're reading in now.

I'll get that fix in the same upcoming release as the ReadGeo fixes.

Cheers,
-jonathan

**Comment by jegstad-dwa** [comment]
This should now be fixed in the latest code updates.

**Comment by jegstad-dwa** [comment]
Hi Morgan,

There was a bug in the instancing support code that caused prim memory to become invalid due to the prim.Load() method destroying the proxy prim.
This is now fixed in the latest commits.

Cheers,
-jonathan

**Comment by morgan-cg** [comment]
Hey Jonathan!  Thanks for the heads up!  We're in the process of updating to your latest build now.  I'll let you know how it works out once I get to test it a bit.  Thanks again!
