### ISSUE TITLE
Nuke USD plugin imports incorrect camera data when it is nested below multiple xform nodes

### ISSUE THREAD

**Issue by morgan-cg** [dreamworksanimation/dwa_usd_plugins#9]
While testing some of our USD camera setups in Nuke, we discovered that if the camera is nested below 4 or 5 xform nodes the plugin does not seem to correctly resolve the final concatenated xform and therefor the camera ends up being off.  

Let me know if there is any additional information that would be helpful in troubleshooting and I'll be happy to try to provide that.

Thanks!
Morgan

**Comment by jegstad-dwa** [comment]
This was a logic error in the separate-parent handling which did not extract the local xform properly.
Also found several other bugs and cleaned up the knob context handling so it's more intuitive.

The biggest secondary bug was the rotation-order extraction from the parent xform did not match the order that the parent rotation was being applied in leading to small rotation differences when switching to/from separate-parent mode.

Fixed in next release.

**Comment by jegstad-dwa** [comment]
Please try out the latest updates posted today, these should solve the matrix concatenation/decomposition issue you're seeing.

Cheers,
-jonathan

**Comment by jegstad-dwa** [comment]
Hi Morgan,
There was a typo in the last update which I'll get an fix published soon for.

In the meantime the mistake is on line 633 of FuserUsd/FuserUsdXform.cpp which should read:
`            if (!axis_vals_list[j].extractFromMatrix(getConcatenatedMatrixAtPrim(xform_prim, timecode),
`
The incorrect line says 'parent_prim' rather than 'xofrm_prim', so in local mode the parent xform was being put into the local xform...whoops.

Cheers,
-jonathan

**Comment by jegstad-dwa** [comment]
Ok, the fix is installed in the repo.

**Comment by jegstad-dwa** [comment]
Hi Morgan,
Have you had a chance to check that this is fixed and the transforms are being decomposed as expected?

Cheers,
-jonathan

**Comment by morgan-cg** [comment]
Hi Jonathan!  Apologies for the delay in giving feedback.  I was able to get access to your new build recently and I'm happy to report that is does look like your fixes did the trick!

Thanks for looking into this issue and the quick turnaround!

Side note, there was another potential bug we came across, though nothing quite as show stopping this time.  But I will go ahead and make a separate issue for that.
